// <auto-generated />
using System;
using FinancialWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialWebApplication.Migrations
{
    [DbContext(typeof(FinancialWebApplicationContext))]
    partial class FinancialWebApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialWebApplication.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountCreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("FinancialWebApplication.Models.AccountDetails", b =>
                {
                    b.Property<string>("AccountKey")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastUpdated")
                        .HasColumnType("date");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("text");

                    b.Property<decimal>("defaultBudget")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)");

                    b.HasKey("AccountKey");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("FinancialWebApplication.Models.MonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountBudget")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)");

                    b.Property<string>("accountKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("budgetMonth")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("monthlyBudget");
                });

            modelBuilder.Entity("FinancialWebApplication.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("AccountKey")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex(new[] { "AccountKey" }, "IndexAccountKey");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinancialWebApplication.Models.Transactions", b =>
                {
                    b.HasOne("FinancialWebApplication.Models.AccountDetails", "AccountDetails")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountKey");

                    b.Navigation("AccountDetails");
                });

            modelBuilder.Entity("FinancialWebApplication.Models.AccountDetails", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
